from __future__ import annotations

SOURCE_MANIFEST_FIELDS = [
    "source_id",
    "city",
    "source_type",
    "source_name",
    "official_or_platform",
    "url_or_page_name",
    "target_table",
    "target_fields",
    "access_method",
    "page_role",
    "source_status",
    "parent_source_id",
    "record_granularity",
    "priority",
    "update_date",
    "last_verified_date",
    "notes",
]

FETCH_LOG_FIELDS = [
    "fetch_time",
    "stage",
    "source_id",
    "city",
    "target_table",
    "source_url",
    "http_status",
    "fetch_mode",
    "blocker_flag",
    "local_path",
    "content_type",
    "note",
]

REGISTRY_PROBE_RESULT_FIELDS = [
    "probe_time",
    "city",
    "parent_source_id",
    "source_id",
    "district",
    "page_role",
    "probe_stage",
    "query_text",
    "candidate_url",
    "candidate_title",
    "status",
    "decision",
    "note",
]

MANUAL_CAPTURE_FIELDS = [
    "manual_id",
    "task_batch",
    "capture_status",
    "city",
    "district",
    "source_id",
    "page_role",
    "parent_source_id",
    "source_page",
    "evidence_type",
    "evidence_title",
    "evidence_url_final",
    "evidence_file_path",
    "evidence_file_sha1",
    "capture_mode",
    "access_channel",
    "public_access_confirmed",
    "captured_at",
    "institution_name_raw",
    "address_raw",
    "phone_raw",
    "operator_name_raw",
    "capacity_raw",
    "registry_status_raw",
    "inclusive_flag_raw",
    "demo_flag_raw",
    "capture_person",
    "import_status",
    "parser_hint",
    "derived_source_id",
    "screenshot_path",
    "remark",
]

MANUAL_REVIEW_FIELDS = [
    "review_id",
    "review_type",
    "ref_table",
    "ref_id",
    "city",
    "district",
    "issue_summary",
    "issue_detail",
    "source_id",
    "manual_action",
    "status",
]

TABLE_SCHEMAS = {
    "source_manifest.csv": [
        ("source_id", "string", "Y", "唯一来源编号"),
        ("city", "string", "Y", "城市名称，ALL 表示跨城市来源"),
        ("source_type", "string", "Y", "来源类别，如 census7、registry_platform"),
        ("source_name", "string", "Y", "来源中文名称"),
        ("official_or_platform", "string", "Y", "official、platform 或 official-linked platform"),
        ("url_or_page_name", "string", "Y", "可访问 URL 或人工页面名称"),
        ("target_table", "string", "Y", "目标落表名称"),
        ("target_fields", "string", "N", "预计抽取字段"),
        ("access_method", "string", "Y", "html_parse、html_parse_ssr、manual_app_capture 等访问方式"),
        ("page_role", "string", "N", "页面角色，如 citywide_entry、organ_search"),
        ("source_status", "string", "N", "来源状态，如 confirmed_direct、manual_required"),
        ("parent_source_id", "string", "N", "父级来源编号"),
        ("record_granularity", "string", "N", "记录粒度，如 city、district、institution"),
        ("priority", "string", "N", "采集优先级，数字越小越优先"),
        ("update_date", "string", "N", "来源页面发布日期或更新时间"),
        ("last_verified_date", "string", "N", "最近一次人工或自动核验日期"),
        ("notes", "string", "N", "补充说明"),
    ],
    "manual_capture_template.csv": [
        ("manual_id", "string", "Y", "人工补录任务编号"),
        ("task_batch", "string", "N", "任务批次"),
        ("capture_status", "string", "Y", "证据采集状态，如 TODO、URL_RECORDED、HAR_EXPORTED"),
        ("city", "string", "Y", "城市名称"),
        ("district", "string", "N", "区县名称"),
        ("source_id", "string", "Y", "来源编号"),
        ("page_role", "string", "N", "页面角色"),
        ("parent_source_id", "string", "N", "父级来源编号"),
        ("source_page", "string", "Y", "需要人工查看的页面或入口描述"),
        ("evidence_type", "string", "N", "证据类型，如 html_snapshot、har、attachment、screenshot、legacy_manual_row"),
        ("evidence_title", "string", "N", "证据页标题或任务标题"),
        ("evidence_url_final", "string", "N", "最终核定后的证据 URL"),
        ("evidence_file_path", "string", "N", "本地证据文件路径"),
        ("evidence_file_sha1", "string", "N", "证据文件 SHA1"),
        ("capture_mode", "string", "N", "采集方式，如 browser_export、direct_download、manual_note"),
        ("access_channel", "string", "N", "访问渠道，如 official_site、app_webview、wechat_h5"),
        ("public_access_confirmed", "string", "N", "是否确认公开可访问"),
        ("captured_at", "string", "N", "证据采集时间"),
        ("institution_name_raw", "string", "N", "机构原始名称"),
        ("address_raw", "string", "N", "机构原始地址"),
        ("phone_raw", "string", "N", "公开电话"),
        ("operator_name_raw", "string", "N", "举办方或运营方原始名称"),
        ("capacity_raw", "string", "N", "公开托位"),
        ("registry_status_raw", "string", "N", "备案状态原始字段"),
        ("inclusive_flag_raw", "string", "N", "原始普惠标记"),
        ("demo_flag_raw", "string", "N", "原始示范标记"),
        ("capture_person", "string", "N", "录入人"),
        ("import_status", "string", "N", "导入状态，如 PENDING、IMPORTED、NORMALIZED、PARSED、FAILED"),
        ("parser_hint", "string", "N", "解析提示，如 attachment_docx_table、har_json_list"),
        ("derived_source_id", "string", "N", "导入后生成的派生来源编号"),
        ("screenshot_path", "string", "N", "证据截图路径"),
        ("remark", "string", "N", "补充备注"),
    ],
    "fetch_log.csv": [
        ("fetch_time", "datetime", "Y", "抓取时间"),
        ("stage", "string", "Y", "抓取阶段"),
        ("source_id", "string", "Y", "来源编号"),
        ("city", "string", "Y", "城市名称"),
        ("target_table", "string", "Y", "目标表"),
        ("source_url", "string", "Y", "请求 URL"),
        ("http_status", "string", "N", "HTTP 状态码"),
        ("fetch_mode", "string", "Y", "normal_tls 或 insecure_tls_retry"),
        ("blocker_flag", "string", "Y", "是否命中 blocker"),
        ("local_path", "string", "N", "落盘路径"),
        ("content_type", "string", "N", "响应类型"),
        ("note", "string", "N", "补充说明"),
    ],
    "registry_probe_results.csv": [
        ("probe_time", "datetime", "Y", "probe 运行时间"),
        ("city", "string", "Y", "城市名称"),
        ("parent_source_id", "string", "N", "父来源编号"),
        ("source_id", "string", "N", "生成或命中的来源编号"),
        ("district", "string", "N", "区县名称"),
        ("page_role", "string", "N", "页面角色"),
        ("probe_stage", "string", "Y", "probe 阶段，如 search、verify、seed"),
        ("query_text", "string", "N", "用于探测的查询文本"),
        ("candidate_url", "string", "N", "候选 URL"),
        ("candidate_title", "string", "N", "候选标题"),
        ("status", "string", "Y", "状态，如 found、blocked、seeded"),
        ("decision", "string", "N", "最终决策"),
        ("note", "string", "N", "补充说明"),
    ],
    "manual_review_list.csv": [
        ("review_id", "string", "Y", "人工复核编号"),
        ("review_type", "string", "Y", "问题类别"),
        ("ref_table", "string", "Y", "关联表名"),
        ("ref_id", "string", "Y", "关联记录 ID"),
        ("city", "string", "N", "城市名称"),
        ("district", "string", "N", "区县名称"),
        ("issue_summary", "string", "Y", "问题概述"),
        ("issue_detail", "string", "N", "问题详情"),
        ("source_id", "string", "N", "来源编号"),
        ("manual_action", "string", "Y", "建议人工动作"),
        ("status", "string", "Y", "初始状态"),
    ],
    "population_city_district.csv": [
        ("pop_record_id", "string", "Y", "人口记录唯一 ID"),
        ("city", "string", "Y", "城市名称"),
        ("district", "string", "N", "区县名称，市级总量为空"),
        ("stat_year", "int", "Y", "统计年份"),
        ("source_id", "string", "Y", "来源编号"),
        ("source_url", "string", "Y", "原始来源 URL"),
        ("indicator_name", "string", "Y", "指标名，如 resident_population"),
        ("indicator_value", "string", "Y", "指标值，保留原始数值表达"),
        ("indicator_unit", "string", "N", "单位，如 person、percent"),
        ("population_scope", "string", "N", "人口口径，如 resident"),
        ("age_group", "string", "N", "年龄分组"),
        ("sex_group", "string", "N", "性别分组"),
        ("urban_rural", "string", "N", "城乡分组"),
        ("note_raw", "string", "N", "原始表头或补充说明"),
        ("extract_method", "string", "Y", "抽取方式"),
        ("manual_check_flag", "string", "Y", "是否需要人工复核"),
    ],
    "nursery_registry_raw.csv": [
        ("raw_row_id", "string", "Y", "原始机构记录 ID"),
        ("city", "string", "Y", "城市名称"),
        ("district", "string", "N", "区县名称"),
        ("registry_batch_name", "string", "N", "批次名称"),
        ("source_id", "string", "Y", "来源编号"),
        ("source_url", "string", "Y", "原始来源 URL"),
        ("source_publish_date", "string", "N", "来源发布日期"),
        ("institution_name_raw", "string", "N", "机构原始名称"),
        ("address_raw", "string", "N", "机构原始地址"),
        ("operator_name_raw", "string", "N", "举办方或运营方原始名称"),
        ("institution_type_raw", "string", "N", "机构类型原始字段"),
        ("registry_status_raw", "string", "N", "备案状态原始字段"),
        ("inclusive_flag_raw", "string", "N", "普惠原始标记"),
        ("demo_flag_raw", "string", "N", "示范原始标记"),
        ("community_flag_raw", "string", "N", "社区嵌入原始标记"),
        ("phone_raw", "string", "N", "公开电话"),
        ("capacity_raw", "string", "N", "公开托位"),
        ("fee_raw", "string", "N", "公开收费"),
        ("raw_text", "string", "N", "原始文本片段"),
        ("parse_status", "string", "Y", "解析状态"),
        ("manual_check_flag", "string", "Y", "是否需要人工复核"),
    ],
    "nursery_master.csv": [
        ("nursery_id", "string", "Y", "主表机构 ID"),
        ("city", "string", "Y", "城市名称"),
        ("district", "string", "N", "区县名称"),
        ("institution_name_std", "string", "Y", "标准化机构名称"),
        ("institution_name_aliases", "string", "N", "别名集合"),
        ("institution_form", "string", "N", "托育机构形态"),
        ("operator_name_std", "string", "N", "标准化举办方名称"),
        ("address_std", "string", "N", "标准化地址"),
        ("source_first_id", "string", "N", "首次出现来源"),
        ("source_latest_id", "string", "N", "最近一次出现来源"),
        ("inclusive_flag", "string", "N", "普惠标记"),
        ("community_embedded_flag", "string", "N", "社区嵌入标记"),
        ("kindergarten_integrated_flag", "string", "N", "托幼一体标记"),
        ("medical_integration_flag", "string", "N", "医育结合标记"),
        ("delayed_tempcare_flag", "string", "N", "延时/临托标记"),
        ("price_transparent_flag", "string", "N", "价格透明标记"),
        ("teacher_emphasis_flag", "string", "N", "师资强调标记"),
        ("chain_brand_flag", "string", "N", "连锁品牌标记"),
        ("registry_evidence_count", "int", "Y", "证据条数"),
        ("geo_status", "string", "Y", "地理编码状态"),
        ("text_status", "string", "Y", "文本抓取状态"),
        ("review_status", "string", "Y", "人工初审状态"),
    ],
    "geo_result.csv": [
        ("geo_id", "string", "Y", "地理编码结果 ID"),
        ("object_type", "string", "Y", "对象类型，当前为 nursery"),
        ("ref_id", "string", "Y", "关联主表 ID"),
        ("city", "string", "Y", "城市名称"),
        ("district", "string", "N", "区县名称"),
        ("address_input", "string", "Y", "输入地址"),
        ("address_std", "string", "N", "标准化地址"),
        ("geocode_source", "string", "Y", "编码来源"),
        ("formatted_address", "string", "N", "高德返回格式化地址"),
        ("province", "string", "N", "省份"),
        ("city_name", "string", "N", "高德返回城市"),
        ("district_name", "string", "N", "高德返回区县"),
        ("township", "string", "N", "高德返回街镇"),
        ("adcode", "string", "N", "高德 adcode"),
        ("lng_gcj02", "string", "N", "GCJ-02 经度"),
        ("lat_gcj02", "string", "N", "GCJ-02 纬度"),
        ("geocode_level", "string", "N", "定位级别"),
        ("source_id", "string", "Y", "来源编号"),
        ("geocode_time", "datetime", "Y", "编码时间"),
        ("manual_check_flag", "string", "Y", "是否需要人工复核"),
    ],
    "poi_residential.csv": [
        ("poi_row_id", "string", "Y", "POI 记录 ID"),
        ("poi_group", "string", "Y", "residential"),
        ("city", "string", "Y", "城市名称"),
        ("district", "string", "N", "区县名称"),
        ("query_keyword", "string", "Y", "查询关键词"),
        ("query_type_code", "string", "N", "查询 typecode"),
        ("adcode", "string", "N", "查询 adcode"),
        ("search_mode", "string", "Y", "搜索模式"),
        ("source_id", "string", "Y", "来源编号"),
        ("poi_id", "string", "N", "高德 POI ID"),
        ("poi_name", "string", "N", "POI 名称"),
        ("poi_type", "string", "N", "POI 类型"),
        ("poi_typecode", "string", "N", "POI 类型编码"),
        ("address", "string", "N", "POI 地址"),
        ("location_gcj02", "string", "N", "经纬度拼接字符串"),
        ("tel", "string", "N", "公开电话"),
        ("parent_id", "string", "N", "父级 POI ID"),
        ("business_area", "string", "N", "商圈"),
        ("query_batch_id", "string", "Y", "查询批次 ID"),
        ("duplicate_flag", "string", "Y", "去重标记"),
        ("manual_check_flag", "string", "Y", "是否需要人工复核"),
    ],
    "poi_support.csv": [
        ("poi_row_id", "string", "Y", "POI 记录 ID"),
        ("poi_group", "string", "Y", "support"),
        ("city", "string", "Y", "城市名称"),
        ("district", "string", "N", "区县名称"),
        ("query_keyword", "string", "Y", "查询关键词"),
        ("query_type_code", "string", "N", "查询 typecode"),
        ("adcode", "string", "N", "查询 adcode"),
        ("search_mode", "string", "Y", "搜索模式"),
        ("source_id", "string", "Y", "来源编号"),
        ("poi_id", "string", "N", "高德 POI ID"),
        ("poi_name", "string", "N", "POI 名称"),
        ("poi_type", "string", "N", "POI 类型"),
        ("poi_typecode", "string", "N", "POI 类型编码"),
        ("address", "string", "N", "POI 地址"),
        ("location_gcj02", "string", "N", "经纬度拼接字符串"),
        ("tel", "string", "N", "公开电话"),
        ("parent_id", "string", "N", "父级 POI ID"),
        ("business_area", "string", "N", "商圈"),
        ("query_batch_id", "string", "Y", "查询批次 ID"),
        ("duplicate_flag", "string", "Y", "去重标记"),
        ("manual_check_flag", "string", "Y", "是否需要人工复核"),
    ],
    "text_raw.csv": [
        ("text_id", "string", "Y", "文本记录 ID"),
        ("nursery_id", "string", "Y", "机构主表 ID"),
        ("city", "string", "Y", "城市名称"),
        ("district", "string", "N", "区县名称"),
        ("source_id", "string", "Y", "来源编号"),
        ("source_url", "string", "Y", "原始文本页面"),
        ("page_title", "string", "N", "页面标题"),
        ("body_text", "string", "Y", "正文纯文本"),
        ("public_phone_if_any", "string", "N", "页面公开电话"),
        ("public_price_if_any", "string", "N", "页面公开价格"),
        ("capture_time", "datetime", "Y", "抓取或入库时间"),
        ("manual_check_flag", "string", "Y", "是否需要人工复核"),
    ],
    "text_tag_suggest.csv": [
        ("text_id", "string", "Y", "文本记录 ID"),
        ("nursery_id", "string", "Y", "机构主表 ID"),
        ("ai_tag", "string", "N", "规则建议标签"),
        ("rule_hit_detail", "string", "N", "命中规则详情"),
        ("human_tag_final", "string", "N", "人工最终标签"),
        ("reviewer", "string", "N", "复核人"),
        ("review_date", "string", "N", "复核日期"),
    ],
    "registry_minimums_report.csv": [
        ("check_id", "string", "Y", "校验编号"),
        ("scope_type", "string", "Y", "范围类型，如 city 或 pipeline"),
        ("scope_value", "string", "Y", "范围值"),
        ("metric_name", "string", "Y", "指标名"),
        ("metric_value", "string", "Y", "指标值"),
        ("threshold", "string", "N", "阈值"),
        ("pass_flag", "string", "Y", "是否通过"),
        ("note", "string", "N", "补充说明"),
    ],
}

TEXT_TAG_RULES = [
    ("普惠", [r"普惠", r"普惠托育", r"普惠性"]),
    ("社区嵌入", [r"社区嵌入", r"嵌入式", r"社区办", r"社区点", r"家门口"]),
    ("托幼一体", [r"托幼一体", r"托幼结合", r"托班", r"幼儿园托班", r"幼托一体"]),
    ("医育结合", [r"医育结合", r"儿童保健", r"儿保", r"妇幼保健", r"医院合作", r"保健医生"]),
    ("延时/临托", [r"延时服务", r"延时托", r"临时托", r"临托", r"计时托", r"半日托", r"小时托"]),
    ("价格透明", [r"收费标准", r"价格公示", r"收费公示", r"月费", r"托育费", r"保育费"]),
    ("师资强调", [r"师资", r"教师资格", r"育婴师", r"保育员", r"早教师", r"持证上岗"]),
    ("连锁品牌", [r"连锁", r"品牌", r"直营网", r"直营网点", r"旗下园所", r"直营"]),
]

DEFAULT_CITY_ADCODES = {
    "南京": "320100",
    "苏州": "320500",
    "南通": "320600",
    "盐城": "320900",
}

DEFAULT_RESIDENTIAL_KEYWORDS = ["小区", "花园", "苑", "城", "公寓"]
DEFAULT_SUPPORT_KEYWORDS = ["地铁站", "公交站", "社区卫生服务中心", "妇幼保健院", "医院"]
